# Generated by Django 4.2.1 on 2023-06-02 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_directory_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="directory",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="directory/default.png", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="directory",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="directory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
